const fs=require('fs'),vm=require('vm'),assert=require('assert');const listeners={};const elements=new Map();const el=s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',style:{},open:false,classList:{remove(){},add(){},toggle(){}},showModal(){this.open=true},close(){this.open=false},scrollIntoView(){},setAttribute(){}});return elements.get(s)};class FD{constructor(f){this.v=f.values||{}}get(k){let v=this.v[k];return Array.isArray(v)?v[0]:v??null}getAll(k){let v=this.v[k];return Array.isArray(v)?v:v==null?[]:[v]}*[Symbol.iterator](){for(let[k,v]of Object.entries(this.v))yield[k,Array.isArray(v)?v[0]:v]}}
const ctx=vm.createContext({console,structuredClone,localStorage:{getItem(){return null},setItem(){}},document:{querySelector:el,querySelectorAll(){return[]},addEventListener(k,v){(listeners[k]??=[]).push(v)}},window:{addEventListener(){}},location:{hash:''},history:{replaceState(){}},setTimeout(){return 1},clearTimeout(){},FormData:FD,Blob,URL,Date,Math,Set,Number,String,Error});for(const f of ['app.js','grooming.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../MatilhaOS',f),'utf8'),ctx);const run=s=>vm.runInContext(s,ctx);let count=0;function test(name,fn){fn();count++;console.log('PASS',name)}function submit(kind,values){el('#formerror').textContent='';let f={values,dataset:{groomForm:kind}};listeners.submit[1]({preventDefault(){},target:{closest(){return f}}});return el('#formerror').textContent}
test('all grooming views render',()=>{for(const tab of ['agenda','atendimentos','historico','servicos','profissionais'])assert(run(`page='grooming';groomMode='${tab}';groomingView()`).length>100)});
test('overlapping professional appointment rejected',()=>assert.throws(()=>run("gValidateAppointment(new FormData({values:{dog:'d4',service:'gs1',professional:'gp1',date:TODAY,time:'10:30'}}))"),/Conflito/));
test('same pet overlap with other professional rejected',()=>assert.throws(()=>run("gValidateAppointment(new FormData({values:{dog:'d1',service:'gs1',professional:'gp2',date:TODAY,time:'10:30'}}))"),/Conflito/));
test('service ending outside hours rejected',()=>assert.throws(()=>run("gValidateAppointment(new FormData({values:{dog:'d1',service:'gs4',professional:'gp1',date:TODAY,time:'17:00'}}))"),/horário/));
test('closed day rejected',()=>assert.throws(()=>run("gValidateAppointment(new FormData({values:{dog:'d1',service:'gs1',professional:'gp1',date:'2026-09-19',time:'10:00'}}))"),/funciona/));
test('correct size price and duration',()=>{let a=run("gValidateAppointment(new FormData({values:{dog:'d1',service:'gs1',professional:'gp1',date:TODAY,time:'11:00'}}))");assert.equal(a.price,100);assert.equal(a.duration,60)});
test('arrival checklist enforced',()=>assert(submit('receive:ga1',{arrival:'10:00',coat:'Sem nós'}).includes('Confira')));
assert.equal(submit('receive:ga1',{arrival:'10:00',coat:'Sem nós',review:'on',belongings:['Guia']}),'');test('arrival recorded',()=>assert.equal(run("ga('ga1').status"),'Recebido'));
assert.equal(submit('start:ga1',{start:'10:00'}),'');test('care starts after receipt',()=>assert.equal(run("ga('ga1').status"),'Em atendimento'));
assert.equal(submit('extra:ga1',{service:'Hidratação',qty:'1',agreed:'on'}),'');assert.equal(submit('finish:ga1',{finished:'11:00',result:'Banho e hidratação concluídos.',checked:'on'}),'');test('completion creates invoice with extras',()=>{assert.equal(run("ga('ga1').status"),'Pronto');assert.equal(run("total(state.invoices.find(f=>f.grooming==='ga1'))"),130)});
submit('finish:ga1',{finished:'11:00',result:'Banho concluído.',checked:'on'});test('repeat completion does not duplicate invoice',()=>assert.equal(run("state.invoices.filter(f=>f.grooming==='ga1').length"),1));
test('unauthorized pickup rejected',()=>assert(submit('deliver:ga1',{responsible:'Desconhecido',delivered:'11:30',returned:['Guia'],summary:'on'}).includes('autorizada')));
test('belongings checked before pickup',()=>assert(submit('deliver:ga1',{responsible:'Mariana Costa',delivered:'11:30',summary:'on'}).includes('pertences')));
assert.equal(submit('deliver:ga1',{responsible:'Mariana Costa',delivered:'11:30',returned:['Guia'],summary:'on'}),'');test('authorized pickup completes journey',()=>assert.equal(run("ga('ga1').status"),'Entregue'));
assert.equal(submit('cancel:ga3',{reason:'Tutor solicitou reagendamento'}),'');test('cancelled appointment releases slot',()=>{let a=run("gValidateAppointment(new FormData({values:{dog:'d2',service:'gs1',professional:'gp1',date:TODAY,time:'14:00'}}))");assert.equal(a.time,'14:00')});
test('monitor cannot schedule',()=>{run("state.role='Monitor'");assert(submit('appointment:',{dog:'d2',service:'gs1',professional:'gp1',date:'2026-09-17',time:'14:00'}).includes('perfil'));run("state.role='Gestor'")});
test('unit filter isolates grooming',()=>{run("state.unit='pinheiros'");assert.equal(run('gList().length'),0)});console.log(count+' grooming test groups passed');
